-- migrations/initial.sql
-- Postgres migration for "Мини‑ферма"
--   - DDL: tables
--   - Indexes
--   - Seed data
--   - Helper functions for atomic ops: buy_seeds, buy_field, plant, harvest, sell
-- Run with: psql -U postgres -h <host> -d farmdb -f migrations/initial.sql

BEGIN;

-- 1) Extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 2) Tables
CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  login VARCHAR(100) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  balance NUMERIC(12,2) NOT NULL DEFAULT 0,
  total_earned NUMERIC(12,2) NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS crop_types (
  id SERIAL PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  seed_price NUMERIC(10,2) NOT NULL,
  grow_duration_seconds INT NOT NULL,
  sell_price NUMERIC(10,2) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS fields (
  id SERIAL PRIMARY KEY,
  user_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  slot_index INT NOT NULL,
  purchased_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (user_id, slot_index)
);

CREATE TABLE IF NOT EXISTS plantings (
  id SERIAL PRIMARY KEY,
  field_id INT NOT NULL REFERENCES fields(id) ON DELETE CASCADE,
  crop_type_id INT NOT NULL REFERENCES crop_types(id),
  quantity INT NOT NULL DEFAULT 1,
  planted_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  ready_at TIMESTAMPTZ NOT NULL,
  harvested BOOLEAN NOT NULL DEFAULT FALSE,
  harvested_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS seed_inventory (
  id SERIAL PRIMARY KEY,
  user_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  crop_type_id INT NOT NULL REFERENCES crop_types(id),
  quantity INT NOT NULL DEFAULT 0,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (user_id, crop_type_id)
);

CREATE TABLE IF NOT EXISTS harvest_inventory (
  id SERIAL PRIMARY KEY,
  user_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  crop_type_id INT NOT NULL REFERENCES crop_types(id),
  quantity INT NOT NULL DEFAULT 0,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (user_id, crop_type_id)
);

CREATE TABLE IF NOT EXISTS transactions (
  id BIGSERIAL PRIMARY KEY,
  user_id INT NOT NULL REFERENCES users(id),
  amount NUMERIC(12,2) NOT NULL,      -- положительное = приход, отрицательное = расход
  type VARCHAR(50) NOT NULL,          -- e.g. 'buy_seeds','sell_crop','buy_field','planting_fee'
  meta JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 3) Indexes
CREATE INDEX IF NOT EXISTS idx_plantings_ready_at ON plantings (ready_at);
CREATE INDEX IF NOT EXISTS idx_fields_user ON fields (user_id);
CREATE INDEX IF NOT EXISTS idx_seedinv_user ON seed_inventory (user_id);
CREATE INDEX IF NOT EXISTS idx_harvestinv_user ON harvest_inventory (user_id);
CREATE INDEX IF NOT EXISTS idx_transactions_user ON transactions (user_id);
-- 4) Seed data (example crops + test user)
INSERT INTO crop_types (name, seed_price, grow_duration_seconds, sell_price)
VALUES
  ('Carrot', 5.00, 60, 10.00),
  ('Potato', 10.00, 120, 22.00),
  ('Wheat', 2.50, 30, 4.50)
ON CONFLICT (name) DO NOTHING;

-- NOTE: replace <bcrypt_hash_here> with an actual bcrypt/argon2 hash generated by your backend
INSERT INTO users (login, password_hash, balance)
VALUES ('test', '<bcrypt_hash_here>', 200.00)
ON CONFLICT (login) DO NOTHING;

COMMIT;


-- 5) Helper functions (atomic operations)
-- 5.1 buy_seeds(user_id, crop_type_id, qty)
-- Returns JSON: { success: bool, message: text, new_balance: numeric }
CREATE OR REPLACE FUNCTION fn_buy_seeds(p_user_id INT, p_crop_type_id INT, p_qty INT)
RETURNS JSONB
LANGUAGE plpgsql
AS $$
DECLARE
  v_price NUMERIC(12,2);
  v_total NUMERIC(12,2);
  v_balance NUMERIC(12,2);
BEGIN
  IF p_qty <= 0 THEN
    RETURN jsonb_build_object('success', false, 'message', 'Invalid quantity');
  END IF;

  SELECT seed_price INTO v_price FROM crop_types WHERE id = p_crop_type_id;
  IF NOT FOUND THEN
    RETURN jsonb_build_object('success', false, 'message', 'Crop type not found');
  END IF;

  v_total := (v_price * p_qty)::NUMERIC(12,2);

  -- Lock user row
  SELECT balance INTO v_balance FROM users WHERE id = p_user_id FOR UPDATE;
  IF v_balance IS NULL THEN
    RETURN jsonb_build_object('success', false, 'message', 'User not found');
  END IF;

  IF v_balance < v_total THEN
    RETURN jsonb_build_object('success', false, 'message', 'Insufficient balance');
  END IF;

  -- Deduct balance
  UPDATE users SET balance = (balance - v_total) WHERE id = p_user_id;

  -- Upsert seed_inventory
  INSERT INTO seed_inventory (user_id, crop_type_id, quantity, updated_at)
  VALUES (p_user_id, p_crop_type_id, p_qty, now())
  ON CONFLICT (user_id, crop_type_id) DO UPDATE
    SET quantity = seed_inventory.quantity + EXCLUDED.quantity,
        updated_at = now();

  -- Insert transaction
  INSERT INTO transactions (user_id, amount, type, meta)
  VALUES (p_user_id, -v_total, 'buy_seeds',
          jsonb_build_object('crop_type_id', p_crop_type_id, 'qty', p_qty));

  -- Return success + new balance
  SELECT balance INTO v_balance FROM users WHERE id = p_user_id;
  RETURN jsonb_build_object('success', true, 'message', 'Bought seeds', 'new_balance', v_balance);
END;
$$;


-- 5.2 buy_field(user_id, slot_index, price)
-- price passed in (allows dynamic pricing); returns JSON
CREATE OR REPLACE FUNCTION fn_buy_field(p_user_id INT, p_slot_index INT, p_price NUMERIC)
RETURNS JSONB
LANGUAGE plpgsql
AS $$
DECLARE
  v_balance NUMERIC(12,2);
BEGIN
  IF p_slot_index <= 0 THEN
    RETURN jsonb_build_object('success', false, 'message', 'Invalid slot index');
  END IF;

  SELECT balance INTO v_balance FROM users WHERE id = p_user_id FOR UPDATE;
  IF v_balance IS NULL THEN
    RETURN jsonb_build_object('success', false, 'message', 'User not found');
  END IF;

  IF v_balance < p_price THEN
    RETURN jsonb_build_object('success', false, 'message', 'Insufficient balance');
  END IF;

  -- Ensure slot not already owned
  IF EXISTS(SELECT 1 FROM fields WHERE user_id = p_user_id AND slot_index = p_slot_index) THEN
    RETURN jsonb_build_object('success', false, 'message', 'Slot already owned');
  END IF;

  -- Deduct balance
  UPDATE users SET balance = (balance - p_price) WHERE id = p_user_id;

  -- Insert field
  INSERT INTO fields (user_id, slot_index, purchased_at)
  VALUES (p_user_id, p_slot_index, now());

  INSERT INTO transactions (user_id, amount, type, meta)
  VALUES (p_user_id, -p_price, 'buy_field', jsonb_build_object('slot_index', p_slot_index));

  SELECT balance INTO v_balance FROM users WHERE id = p_user_id;
  RETURN jsonb_build_object('success', true, 'message', 'Field purchased', 'new_balance', v_balance);
END;
$$;
-- 5.3 plant(user_id, field_id, crop_type_id, qty)
-- Computes ready_at = now() + grow_duration_seconds
CREATE OR REPLACE FUNCTION fn_plant(p_user_id INT, p_field_id INT, p_crop_type_id INT, p_qty INT)
RETURNS JSONB
LANGUAGE plpgsql
AS $$
DECLARE
  v_field_user INT;
  v_have_seeds INT;
  v_grow_sec INT;
  v_ready TIMESTAMPTZ;
BEGIN
  IF p_qty <= 0 THEN
    RETURN jsonb_build_object('success', false, 'message', 'Invalid quantity');
  END IF;

  -- Verify field belongs to user
  SELECT user_id INTO v_field_user FROM fields WHERE id = p_field_id;
  IF v_field_user IS NULL OR v_field_user <> p_user_id THEN
    RETURN jsonb_build_object('success', false, 'message', 'Field not found or not owned');
  END IF;

  -- Ensure no active planting on this field
  IF EXISTS (SELECT 1 FROM plantings WHERE field_id = p_field_id AND harvested = FALSE) THEN
    RETURN jsonb_build_object('success', false, 'message', 'Field is occupied');
  END IF;

  -- Check seeds
  SELECT quantity INTO v_have_seeds FROM seed_inventory WHERE user_id = p_user_id AND crop_type_id = p_crop_type_id FOR UPDATE;
  IF v_have_seeds IS NULL OR v_have_seeds < p_qty THEN
    RETURN jsonb_build_object('success', false, 'message', 'Not enough seeds');
  END IF;

  SELECT grow_duration_seconds INTO v_grow_sec FROM crop_types WHERE id = p_crop_type_id;
  IF v_grow_sec IS NULL THEN
    RETURN jsonb_build_object('success', false, 'message', 'Crop type not found');
  END IF;

  v_ready := now() + (v_grow_sec || ' seconds')::interval;

  -- Deduct seeds
  UPDATE seed_inventory SET quantity = quantity - p_qty, updated_at = now()
  WHERE user_id = p_user_id AND crop_type_id = p_crop_type_id;

  -- Insert planting
  INSERT INTO plantings (field_id, crop_type_id, quantity, planted_at, ready_at, harvested)
  VALUES (p_field_id, p_crop_type_id, p_qty, now(), v_ready, FALSE);

  RETURN jsonb_build_object('success', true, 'message', 'Planted', 'ready_at', to_char(v_ready AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'));
END;
$$;


-- 5.4 harvest(user_id, field_id)
-- Marks planting as harvested, moves quantity to harvest_inventory
CREATE OR REPLACE FUNCTION fn_harvest(p_user_id INT, p_field_id INT)
RETURNS JSONB
LANGUAGE plpgsql
AS $$
DECLARE
  v_plant_id INT;
  v_crop_type INT;
  v_qty INT;
  v_ready TIMESTAMPTZ;
  v_field_user INT;
BEGIN
  -- verify ownership of field
  SELECT user_id INTO v_field_user FROM fields WHERE id = p_field_id;
  IF v_field_user IS NULL OR v_field_user <> p_user_id THEN
    RETURN jsonb_build_object('success', false, 'message', 'Field not found or not owned');
  END IF;

  SELECT id, crop_type_id, quantity, ready_at, harvested INTO v_plant_id, v_crop_type, v_qty, v_ready, v_plant_id
  FROM plantings
  WHERE field_id = p_field_id AND harvested = FALSE
  LIMIT 1;

  -- Note: above SELECT assigned v_plant_id twice due to reuse; fix by separate SELECT
  IF v_plant_id IS NULL THEN
    -- Re-do proper select
    SELECT id, crop_type_id, quantity, ready_at, harvested INTO v_plant_id, v_crop_type, v_qty, v_ready, v_plant_id
    FROM plantings
    WHERE field_id = p_field_id AND harvested = FALSE
    LIMIT 1;
  END IF;

  -- Simpler correct select:
  SELECT id, crop_type_id, quantity, ready_at INTO v_plant_id, v_crop_type, v_qty, v_ready
  FROM plantings
  WHERE field_id = p_field_id AND harvested = FALSE
  LIMIT 1;

  IF v_plant_id IS NULL THEN
    RETURN jsonb_build_object('success', false, 'message', 'No active planting found');
  END IF;

  IF now() < v_ready THEN
    RETURN jsonb_build_object('success', false, 'message', 'Not ready for harvest');
  END IF;

  -- Mark planting as harvested
  UPDATE plantings SET harvested = TRUE, harvested_at = now() WHERE id = v_plant_id;
-- Upsert into harvest_inventory
  INSERT INTO harvest_inventory (user_id, crop_type_id, quantity, updated_at)
  VALUES (p_user_id, v_crop_type, v_qty, now())
  ON CONFLICT (user_id, crop_type_id) DO UPDATE
    SET quantity = harvest_inventory.quantity + EXCLUDED.quantity,
        updated_at = now();

  RETURN jsonb_build_object('success', true, 'message', 'Harvested', 'crop_type_id', v_crop_type, 'qty', v_qty);
END;
$$;
-- 5.5 sell(user_id, crop_type_id, qty)
-- Sells harvested crops: decreases harvest_inventory, increases balance and total_earned, inserts transaction
CREATE OR REPLACE FUNCTION fn_sell(p_user_id INT, p_crop_type_id INT, p_qty INT)
RETURNS JSONB
LANGUAGE plpgsql
AS $$
DECLARE
  v_have INT;
  v_price NUMERIC(12,2);
  v_total NUMERIC(12,2);
BEGIN
  IF p_qty <= 0 THEN
    RETURN jsonb_build_object('success', false, 'message', 'Invalid quantity');
  END IF;

  SELECT quantity INTO v_have FROM harvest_inventory WHERE user_id = p_user_id AND crop_type_id = p_crop_type_id FOR UPDATE;
  IF v_have IS NULL OR v_have < p_qty THEN
    RETURN jsonb_build_object('success', false, 'message', 'Not enough harvested crops');
  END IF;

  SELECT sell_price INTO v_price FROM crop_types WHERE id = p_crop_type_id;
  IF v_price IS NULL THEN
    RETURN jsonb_build_object('success', false, 'message', 'Crop type not found');
  END IF;

  v_total := (v_price * p_qty)::NUMERIC(12,2);

  -- Deduct harvest inventory
  UPDATE harvest_inventory SET quantity = quantity - p_qty, updated_at = now()
  WHERE user_id = p_user_id AND crop_type_id = p_crop_type_id;

  -- Increment user balance and total_earned
  UPDATE users SET balance = balance + v_total, total_earned = total_earned + v_total WHERE id = p_user_id;

  -- Transaction record
  INSERT INTO transactions (user_id, amount, type, meta)
  VALUES (p_user_id, v_total, 'sell_crop', jsonb_build_object('crop_type_id', p_crop_type_id, 'qty', p_qty));

  SELECT balance INTO v_price FROM users WHERE id = p_user_id; -- reuse v_price var to fetch balance
  RETURN jsonb_build_object('success', true, 'message', 'Sold', 'revenue', v_total, 'new_balance', v_price);
END;
$$;
-- 6) Helpful view for farm/fields JSON (example)
-- This view returns server_now and a JSON array of fields + optional planting
CREATE OR REPLACE VIEW vw_user_fields AS
SELECT
  f.user_id,
  to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"') AS server_now,
  json_agg(json_build_object(
    'id', f.id,
    'slotIndex', f.slot_index,
    'purchasedAt', to_char(f.purchased_at AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'),
    'planting',
      CASE WHEN p.id IS NULL THEN NULL
        ELSE json_build_object(
          'id', p.id,
          'cropTypeId', p.crop_type_id,
          'cropName', ct.name,
          'quantity', p.quantity,
          'plantedAt', to_char(p.planted_at AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'),
          'readyAt', to_char(p.ready_at AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'),
          'harvested', p.harvested
        )
      END
  ) ORDER BY f.slot_index) AS fields
FROM fields f
LEFT JOIN plantings p ON p.field_id = f.id AND p.harvested = FALSE
LEFT JOIN crop_types ct ON ct.id = p.crop_type_id
GROUP BY f.user_id;


-- 7) Example helper query for leaderboard
CREATE OR REPLACE VIEW vw_leaderboard AS
SELECT
  ROW_NUMBER() OVER (ORDER BY u.balance DESC) AS place,
  u.login,
  u.balance,
  u.total_earned AS extra_metric
FROM users u
ORDER BY u.balance DESC;


-- 8) Notes for usage:
--   - The functions return JSONB with success/message; backend can call them via SQL and parse result.
--   - All timestamps use UTC. Frontend expects ISO8601 strings.
--   - Replace password hash in seed or create users via backend endpoints.

-- 9) Cleanup any incomplete placeholder SELECTs (safety)
-- (No-op here)

-- End of migration