
-- Это расширение позволяет генерировать UUID (GUID) значения,
-- которые часто используются в качестве первичных ключей в .NET приложениях.
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Эта таблица хранит информацию о типах культур, которые можно сажать/продавать.
-- Id: уникальный идентификатор типа культуры.
-- Name: название культуры (например, "Морковь").
-- SeedPrice: цена за одно семя культуры.
-- GrowSeconds: время созревания культуры в секундах.
-- SellPrice: цена, по которой можно продать урожай.
CREATE TABLE IF NOT EXISTS "CropTypes" (
    "Id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name" TEXT NOT NULL,
    "SeedPrice" NUMERIC(18,2) NOT NULL,
    "GrowSeconds" INT NOT NULL,
    "SellPrice" NUMERIC(18,2) NOT NULL
);

INSERT INTO "CropTypes" ("Name", "SeedPrice", "GrowSeconds", "SellPrice")
VALUES
    ('Морковь', 10.00, 60, 15.00),      -- Морковь: быстро растёт, низкая цена
    ('Картофель', 25.00, 180, 40.00),   -- Картофель: среднее время роста и цена
    ('Клубника', 50.00, 300, 90.00)     -- Клубника: долго растёт, высокая цена
ON CONFLICT ("Name") DO NOTHING;